fix security issue when token was exposed trhough interpolation

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -60,6 +60,11 @@ runs:
 
 ## Phase 0 - Init: validate inputs, infer defaults, login in AWS
 
+    - name: Validate npmjs token
+      if: inputs.npmjs-token && inputs.dev-release
+      shell: bash
+      run: echo "Error: npmjs does not support dev-release (version inferred from branch name), npmjs only supports semver" >&2; exit 1
+
     - name: Init
       id: init
       shell: bash
@@ -67,12 +72,6 @@ runs:
         # this action is called in context of the microservice repo, so GITHUB_REPOSITORY has a format of 'company/service'
         service=$(echo "${GITHUB_REPOSITORY}" | awk -F'/' '{print $2}')
         echo "service=$service" >> $GITHUB_OUTPUT
-        
-        # add check that in inputs.npmjs-token is provided and dev-release is true then error out
-        if [ -n "${{ inputs.npmjs-token }}" ] && [ "${{ inputs.dev-release }}" = "true" ]; then
-          echo "Error: npmjs does not support dev-release (version inferred from branch name), npmjs only supports semver" >&2
-          exit 1
-        fi
         
         if [ "${{ inputs.dev-release }}" = "true" ] && [ -n "${{ inputs.dev-branch-prefix }}" ]; then
           branch="${GITHUB_REF#refs/heads/}"
